% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Jun-2021 20:09:31
%  MATLAB version: 9.8.0.1323502 (R2020a)
% -------------------------------------------------------------------
saveVarsMat = load('tugas4.mat');

a = [1 1 1 0];

net = saveVarsMat.net; % <1x1 network> unsupported class

p = ...
  [1 1 0 0;
   1 0 1 0];

t = [1 1 1 0];

clear saveVarsMat;
